---
- name: Copy app files to frontend
  hosts: frontend
  become: true
  
  tasks:
    - name: Copy app files to frontend machine
      ansible.posix.synchronize:
        src: ./app
        dest: /home/ubuntu
        rsync_opts:
          - "--exclude=**/python"
          - "--chown=ubuntu:ubuntu"
